let all=[],view=[];
const fmt=n=>new Intl.NumberFormat("ru-RU").format(n||0)+" ₽";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const labels={new:"Новый",work:"В работе",bid:"Подана заявка",no:"Не берём",win:"Выигран",lost:"Проигран"};
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toISOString();
const eventLabels={found:"Тендер найден",seen:"Повторно найден при поиске",status:"Изменён статус",date:"Изменена дата решения",note:"Добавлен комментарий"};
function historyEvent(type,details=""){return{at:now(),type,details}}
async function load(){const s=await chrome.storage.local.get(["kitTenders","lastRun"]);all=(s.kitTenders||[]).map(x=>{const first=x.firstSeenAt||x.foundAt||x.publicationDate||now();return{...x,workStatus:x.workStatus||"new",decisionDate:x.decisionDate||"",firstSeenAt:first,lastSeenAt:x.lastSeenAt||first,history:Array.isArray(x.history)&&x.history.length?x.history:[{at:first,type:"found",details:"Добавлен в базу радара"}]}});document.getElementById("updated").textContent=s.lastRun?new Date(s.lastRun).toLocaleString("ru-RU"):"—";render()}
async function saveItem(id,patch,eventType,details){const i=all.findIndex(x=>x.id===id);if(i<0)return;const item=all[i];const history=[...(item.history||[])];if(eventType)history.push(historyEvent(eventType,details));all[i]={...item,...patch,history};await chrome.storage.local.set({kitTenders:all});render()}
function statusOptions(value){return Object.entries(labels).map(([k,v])=>`<option value="${k}" ${value===k?"selected":""}>${v}</option>`).join("")}
function render(){
 const q=document.getElementById("q").value.toLowerCase(),src=document.getElementById("source").value,min=+document.getElementById("score").value,ws=document.getElementById("workStatus").value;
 view=all.filter(x=>(src==="Все источники"||x.source===src)&&(x.score||0)>=min&&(!ws||(x.workStatus||"new")===ws)&&((x.title||"")+" "+(x.customer||"")+" "+(x.inn||"")).toLowerCase().includes(q));
 document.getElementById("count").textContent=view.length;
 document.getElementById("inwork").textContent=all.filter(x=>["work","bid"].includes(x.workStatus)).length;
 document.getElementById("declined").textContent=all.filter(x=>x.workStatus==="no").length;
 document.getElementById("empty").style.display=view.length?"none":"block";
 document.getElementById("body").innerHTML=view.map(x=>`<tr><td><a href="${esc(x.url)}" target="_blank">${esc(x.title||"Без названия")}</a><div style="color:#76828e;font-size:11px;margin-top:5px">${esc(x.customer||"")} ${x.inn?"· ИНН "+esc(x.inn):""}</div></td><td><span class="tag">${esc(x.source||"")}</span></td><td><b>${fmt(x.price)}</b></td><td>${esc(x.publicationDate||"—")}</td><td>${esc(x.deadline||"—")}</td><td><span class="score">${x.score||65}</span></td><td><select class="work-select st-${x.workStatus||"new"}" data-id="${esc(x.id)}">${statusOptions(x.workStatus||"new")}</select></td><td><input class="date-input" data-id="${esc(x.id)}" type="date" value="${esc(x.decisionDate||"")}"></td><td><button class="history-btn" data-id="${esc(x.id)}">История (${(x.history||[]).length})</button></td></tr>`).join("");
 document.querySelectorAll(".work-select").forEach(el=>el.onchange=()=>{const item=all.find(x=>x.id===el.dataset.id),old=labels[item?.workStatus||"new"],next=labels[el.value];saveItem(el.dataset.id,{workStatus:el.value,decisionDate:item?.decisionDate||(el.value==="new"?"":today())},"status",old+" → "+next)});
 document.querySelectorAll(".date-input").forEach(el=>el.onchange=()=>{const item=all.find(x=>x.id===el.dataset.id);saveItem(el.dataset.id,{decisionDate:el.value},"date",(item?.decisionDate||"не указана")+" → "+(el.value||"не указана"))});
 document.querySelectorAll(".history-btn").forEach(el=>el.onclick=()=>openHistory(el.dataset.id));
}
function openHistory(id){const x=all.find(t=>t.id===id);if(!x)return;document.getElementById("historyTitle").textContent=x.title||"История тендера";document.getElementById("historyMeta").textContent="Первое обнаружение: "+new Date(x.firstSeenAt).toLocaleString("ru-RU")+" · Последнее обнаружение: "+new Date(x.lastSeenAt).toLocaleString("ru-RU");const events=[...(x.history||[])].sort((a,b)=>new Date(b.at)-new Date(a.at));document.getElementById("historyBody").innerHTML=events.length?events.map(e=>`<div class="event"><div class="event-time">${esc(new Date(e.at).toLocaleString("ru-RU"))}</div><div class="event-text">${esc(eventLabels[e.type]||e.type||"Изменение")}</div><div class="event-details">${esc(e.details||"")}</div></div>`).join(""):"<div class=\"empty\">История пока пуста</div>";document.getElementById("historyModal").classList.add("open")}
document.getElementById("historyClose").onclick=()=>document.getElementById("historyModal").classList.remove("open");
document.getElementById("historyModal").onclick=e=>{if(e.target.id==="historyModal")e.currentTarget.classList.remove("open")};
["q","source","score","workStatus"].forEach(id=>document.getElementById(id).addEventListener("input",render));
document.getElementById("collect").onclick=()=>{const b=document.getElementById("collect");b.textContent="Собираю…";chrome.runtime.sendMessage({type:"COLLECT_ALL"},()=>{b.textContent="Обновить список";load()})};
document.getElementById("jsonExport").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),tenders:all},null,2)],{type:"application/json"}));a.download="KIT_Tenders_For_Site.json";a.click()};
document.getElementById("export").onclick=()=>{const rows=[["Тендер","Заказчик","ИНН","Источник","НМЦК","Дата начала","Первое обнаружение","Последнее обнаружение","Дедлайн","Рейтинг","Решение","Дата решения","История изменений","Ссылка"],...view.map(x=>[x.title,x.customer,x.inn,x.source,x.price,x.publicationDate,x.firstSeenAt,x.lastSeenAt,x.deadline,x.score,labels[x.workStatus||"new"],x.decisionDate,(x.history||[]).map(e=>new Date(e.at).toLocaleString("ru-RU")+" — "+(eventLabels[e.type]||e.type)+": "+(e.details||"")).join("\n"),x.url])];const csv=rows.map(r=>r.map(x=>'"'+String(x||"").replaceAll('"','""')+'"').join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download="Тендеры_КИТ_со_статусами.csv";a.click()};
load();